### PR TITLE
Change to CMD shell form

### LINKED ISSUE #748: Golang Start Command
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Nix pack works fine for building a default container. But when I start adding custom start commands, something fails.

# Here is a working build & deploy, without start commands
image
image

Builds fine but it's just using the default start command.

# Here is a build with start commands, it fails

```
==============
Using Nixpacks
==============
context: ed2947ad0e8ecf616927e0060d4c0270
 
╔═══════════════ Nixpacks v1.0.2 ══════════════╗
║ setup      │ go                              ║
║──────────────────────────────────────────────║
║ install    │ go mod download                 ║
║──────────────────────────────────────────────║
║ build      │ go build -o out                 ║
║──────────────────────────────────────────────║
║ start      │ ./out serve --http=0.0.0.0:8080 ║
╚══════════════════════════════════════════════╝
 
 
#1 [internal] load build definition from Dockerfile
 
#1 sha256:e8bb16e8b634bd9bebc0c66b16d603251cefc3f0a6271aa60196a5fd4ae5bff9
#1 transferring dockerfile: 2.22kB done
#1 DONE 0.1s
 
#2 [internal] load .dockerignore
#2 sha256:83ba8f630c928851beada741a87c4013a3d1396fd70fcd285f0cf5b60ba967ae
#2 transferring context: 2B done
#2 DONE 0.1s
 
 
#4 [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1671044363
#4 sha256:d2df4677b7c4c8365aa628f14d4cbdd9867466b6b454c21060180de4b7936a2e
 
#4 DONE 0.2s
 
#3 [internal] load metadata for docker.io/library/ubuntu:jammy
#3 sha256:5e41972c0cdee05640f3ed85ad5e7dca92c5a589ced43badaf14d81466f891ae
 
#3 DONE 0.3s
 
#7 [stage-0 1/8] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1671044363@sha256:4df36f942799b8b727c8648ca4fa05d9cd2526e41e7994665082c0f7ef03d95b
#7 sha256:a20b8f1ac783d9d00f7c673a9ef0cf3b8f0aaee89856a86f7aff78cda1934897
#7 DONE 0.0s
 
#5 [stage-1 1/5] FROM docker.io/library/ubuntu:jammy@sha256:27cb6e6ccef575a4698b66f5de06c7ecd61589132d5a91d098f7f3f9285415a9
#5 sha256:6f3b08c859f255cb37cf3502bfa9aed8c925823cc7863ca0013f3d26e621ba0a
#5 DONE 0.0s
 
#9 [internal] load build context
#9 sha256:5ba5de9ca6e5738400782728f92c78b5d56c3c0483e12cb60e36c0f1f9552217
 
#9 transferring context: 47.88MB 0.3s done
#9 DONE 0.4s
 
#8 [stage-0 2/8] WORKDIR /app/
#8 sha256:46f35bb14209f31cddb6d0e80d42b3ceb58d2f45672a3486e22a069140ac06a3
#8 CACHED
 
#10 [stage-0 3/8] COPY .nixpacks/nixpkgs-ffca9ffaaafb38c8979068cee98b2644bd3f14cb.nix .nixpacks/nixpkgs-ffca9ffaaafb38c8979068cee98b2644bd3f14cb.nix
#10 sha256:70ce6a4b3804a2f877ed74a578551f50633788dede0695d433b48111d338f981
#10 CACHED
 
#11 [stage-0 4/8] RUN nix-env -if .nixpacks/nixpkgs-ffca9ffaaafb38c8979068cee98b2644bd3f14cb.nix && nix-collect-garbage -d
#11 sha256:59b918cc061dba6437fa95b37561145b04058cd12ce1167115d3a26179aa4c47
#11 CACHED
 
#12 [stage-0 5/8] COPY . /app/.
#12 sha256:147cc57d0c70d995b1d9c5abc4d3807c3a8a843574fd4543384d357f8987a46a
 
#12 DONE 0.2s
 
#13 [stage-0 6/8] RUN --mount=type=cache,id=s/0098b1a9-7adb-49c6-8db1-ed7f1c65db8d-/root/cache/go-build,target=/root/.cache/go-build go mod download
#13 sha256:f7e5740124829bd271b77f19fd3cafa34cb163037e849ef9fdf721bfc4647361
 
#13 DONE 8.2s
 
#14 [stage-0 7/8] COPY . /app/.
#14 sha256:8eca9da03455fe36e13e2875747fa89fbbde0b733b9fda696447b4ea3c254394
 
#14 DONE 0.2s
 
 
#15 [stage-0 8/8] RUN --mount=type=cache,id=s/0098b1a9-7adb-49c6-8db1-ed7f1c65db8d-/root/cache/go-build,target=/root/.cache/go-build go build -o out
 
#15 sha256:788c2e178bb565b2ba5742e5f39bca0fea5b6166122b6e8771e53932e3bd5d56
 
#15 DONE 2.7s
 
 
#6 [stage-1 2/5] WORKDIR /app/
#6 sha256:b562f93b81a88474f0a0d1f49b4aedecd6daa1817f0bb2a067dec049c0a7db1c
#6 CACHED

#19 exporting layers done
#19 writing image sha256:b7b25b27a998eb25c2ab8f3d61263df773a08f71720434d031080d1cd237ea45
 
#19 writing image sha256:b7b25b27a998eb25c2ab8f3d61263df773a08f71720434d031080d1cd237ea45 0.0s done
#19 naming to us-west1-docker.pkg.dev/railway-infra/railway-docker-users/project/0c560053-13c4-41e8-b9be-287fe67a6dec/service/0098b1a9-7adb-49c6-8db1-ed7f1c65db8d:9e6482aa-20a2-4721-8060-6098db2fa736 0.0s done
#19 DONE 0.1s
 
#20 exporting cache
#20 sha256:2700d4ef94dee473593c5c614b55b2dedcca7893909811a8f2b48291a1f581e4
#20 preparing build cache for export 0.1s done
#20 DONE 0.1s
 
=== Successfully Built! ===
 
Run:
docker run -it us-west1-docker.pkg.dev/railway-infra/railway-docker-users/project/0c560053-13c4-41e8-b9be-287fe67a6dec/service/0098b1a9-7adb-49c6-8db1-ed7f1c65db8d:9e6482aa-20a2-4721-8060-6098db2fa736
 
Build time: 15.52 seconds
 
================
Publishing Image
================
The push refers to repository [us-west1-docker.pkg.dev/railway-infra/railway-docker-users/project/0c560053-13c4-41e8-b9be-287fe67a6dec/service/0098b1a9-7adb-49c6-8db1-ed7f1c65db8d]
Preparing  07458905b58b
Preparing  5f70bf18a086
Preparing  8112635cc30b
Preparing  1a22f5485129
Preparing  6515074984c6
Waiting  6515074984c6
Layer already exists  8112635cc30b
Layer already exists  5f70bf18a086
Layer already exists  1a22f5485129
Layer already exists  6515074984c6
Pushing [>                                                  ]  546.8kB/98.11MB 07458905b58b
Pushing [=>                                                 ]  2.218MB/98.11MB 07458905b58b
Pushing [=>                                                 ]  3.889MB/98.11MB 07458905b58b
Pushing [==>                                                ]   5.56MB/98.11MB 07458905b58b
Pushing [===>                                               ]  7.231MB/98.11MB 07458905b58b
Pushing [====>                                              ]  8.903MB/98.11MB 07458905b58b
Pushing [=====>                                             ]  11.13MB/98.11MB 07458905b58b
Pushing [======>                                            ]   12.8MB/98.11MB 07458905b58b
Pushing [=======>                                           ]  14.47MB/98.11MB 07458905b58b
Pushing [========>                                          ]   16.7MB/98.11MB 07458905b58b
Pushing [=========>                                         ]  18.93MB/98.11MB 07458905b58b
Pushing [==========>                                        ]  21.16MB/98.11MB 07458905b58b
Pushing [===========>                                       ]  23.39MB/98.11MB 07458905b58b
Pushing [============>                                      ]  25.06MB/98.11MB 07458905b58b
Pushing [==============>                                    ]  28.96MB/98.11MB 07458905b58b
Pushing [================>                                  ]  31.74MB/98.11MB 07458905b58b
Pushing [=================>                                 ]  33.97MB/98.11MB 07458905b58b
Pushing [==================>                                ]   36.2MB/98.11MB 07458905b58b
Pushing [===================>                               ]  37.87MB/98.11MB 07458905b58b
Pushing [=====================>                             ]  41.21MB/98.11MB 07458905b58b
Pushing [======================>                            ]     44MB/98.11MB 07458905b58b
Pushing [=======================>                           ]  46.23MB/98.11MB 07458905b58b
Pushing [========================>                          ]   48.4MB/98.11MB 07458905b58b
Pushing [=========================>                         ]  50.07MB/98.11MB 07458905b58b
Pushing [==========================>                        ]  51.74MB/98.11MB 07458905b58b
Pushing [===========================>                       ]  53.41MB/98.11MB 07458905b58b
Pushing [============================>                      ]  55.09MB/98.11MB 07458905b58b
Pushing [============================>                      ]  56.76MB/98.11MB 07458905b58b
Pushing [==============================>                    ]  58.98MB/98.11MB 07458905b58b
Pushing [==============================>                    ]  60.66MB/98.11MB 07458905b58b
Pushing [===============================>                   ]  62.33MB/98.11MB 07458905b58b
Pushing [================================>                  ]  64.56MB/98.11MB 07458905b58b
Pushing [==================================>                ]  66.78MB/98.11MB 07458905b58b
Pushing [===================================>               ]  69.01MB/98.11MB 07458905b58b
Pushing [====================================>              ]  71.24MB/98.11MB 07458905b58b
Pushing [=====================================>             ]  73.47MB/98.11MB 07458905b58b
Pushing [=======================================>           ]  76.81MB/98.11MB 07458905b58b
Pushing [========================================>          ]  80.15MB/98.11MB 07458905b58b
Pushing [=========================================>         ]  81.82MB/98.11MB 07458905b58b
Pushing [==========================================>        ]   83.5MB/98.11MB 07458905b58b
Pushing [===========================================>       ]  85.72MB/98.11MB 07458905b58b
Pushing [============================================>      ]  87.95MB/98.11MB 07458905b58b
Pushing [=============================================>     ]  90.18MB/98.11MB 07458905b58b
Pushing [===============================================>   ]  92.41MB/98.11MB 07458905b58b
Pushing [================================================>  ]  94.64MB/98.11MB 07458905b58b
Pushing [=================================================> ]  96.31MB/98.11MB 07458905b58b
Pushing [==================================================>]  98.12MB 07458905b58b
Pushed  07458905b58b
9e6482aa-20a2-4721-8060-6098db2fa736: digest: sha256:a3ce8dba1ef09d3c3e0928122f45b9334e174c3c3a60fda4eaf4954b5adda6d4 size: 1366
 
 
========================
Container Start Failure!
========================
rpc error: code = Unknown desc = Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./out serve --http=0.0.0.0:8080": stat ./out serve --http=0.0.0.0:8080: no such file or directory: unknown
 
```

### To reproduce

Build a standard golang application with commands. I am using pocketbase.

Add start commands to add to the run command.

### Expected behavior

The build to go through like standard, but with start commands.

### Environment

Nixpacks 18, on railway

### PR DESCRIPTION
**Pull request by Fish1**
This PR will use the docker CMD shell format. It allows for executables with command line arguments to be run properly.

Original docker that caused start cmd ```./out my args``` to fail.
```
ENTRYPOINT [\"/bin/bahs\", \"-l\", \"-c\"]
CMD ["my command"]
```

This allows any start command to execute
```
CMD my command
```

We can remove the ENTRYPOINT because the new CMD format will run inside a shell.

I ran the test, everything passed up until it hit the ```Doc-tests nixpacks```

closes #748

### CODE REVIEW

**Comment by coffee-cup** [comment]
Unfortunately, I don't think this will work because the `base -l` is necessary to load things in `~/.profile` on container start. (see this PR https://github.com/railwayapp/nixpacks/pull/487 and https://github.com/railwayapp/nixpacks/issues/658)

You can run commands with arguments by quoting everything. E.g. `docker run my-image "./out arg 1 arg2"`

Very open to suggestions on how to have both the CMD format as well as ensuring that everything in `~/.profile` is loaded.

**Comment by Fish1** [comment]
Alright, here are few ideas.

1) The golang start command does not get run as a string. It gets executed in a non-shell CMD, because it does not have an entrypoint.

Resulting in the following 
```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "echo yoooo && ./out hello world \"yo bro\" 1 2 3": stat echo yoooo && ./out hello world "yo bro" 1 2 3: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled 
```

start.run_in_slim_image() adds this to the docker. Adding an entry point here fixes the golang issue.
image

This change passes all tests.
image



2) This is a just a random spitball... but we could just source ~/.profile as the first part of the CMD
image
image

3) sh has a special environment variable ```ENV```. if this environment variable is set, it will execute any files specified in the variable when SH is invoked. Is there something similar for bash, so we can specify an ENV in the dockerfile?
https://stackoverflow.com/questions/38024160/how-to-get-etc-profile-to-run-automatically-in-alpine-docker
image

**Comment by coffee-cup** [comment]
Good suggestions! We should defintely do 1 because that seems like a bug.

I am actually surprised that all the docker run tests pass in this PR. I will confirm that the `-l -c` is still need and if so can add a test that would fail without it. That way we can be sure of any solution moving forward.

**Comment by josegonzalez** [comment]
The alternative could be a simple bash wrapper (like i posted in #658) that we run as the entrypoint:

```
#!/usr/bin/env bash

if [[ "$#" == "1" ]]; then
  exec bash -l -c "$@"
else
  exec bash -l "$@"
fi
```

And then the CMD for the image can just be the command that was passed. This would also allow `docker run` to be executed with arguments on commands vs a quoted command.

**Pull request closed without merging**
