### PR TITLE
Switch PHP prestart from Perl to JS

### PR DESCRIPTION
**Pull request by aleksrutins**
This PR switches the PHP provider's runtime scripts from Perl to JS, removing dependencies and improving maintainability. The only user-facing change is the removal of Perl.

### CODE REVIEW

**Comment by aleksrutins** [comment]
not stale

**Comment by aleksrutins** [comment]
CI failure seems to be unrelated.

**Comment by aleksrutins** [comment]
not stale

**Review by coffee-cup — APPROVED** [review]
This is so much more readable! Sorry it took so long to get reviewed

**Pull request merged**
