### PR TITLE
Add support for newer Swift versions

### PR DESCRIPTION
**Pull request by m1guelpf**
Add support for newer Swift versions.

### CODE REVIEW

**Review by JakeCooper — APPROVED** [review]
Nice! Thanks :D

**Comment by m1guelpf** [comment]
@JakeCooper Should I also update the default version to `5.9`? I held off on doing so originally to prevent breaking changes, but it’s probably a better default for new apps

**Comment by JakeCooper** [comment]
I think it’s okay to bump it to 5.9 given it’s a minor version bump

**Comment by JakeCooper** [comment]
@m1guelpf I think it’s okay to bump it to 5.9 given it’s a minor version bump

**Pull request closed without merging**
