### PR TITLE
Pass environment variables to PHP FPM

### PR DESCRIPTION
**Pull request by deiucanta**
PHP FPM doesn't pass env variables by default but I think it's helpful to disable this behavior. In Docker, a lot of times you want to pass variables via the `-e` flag.

Here is an article about this issue: https://medium.com/@tomahock/passing-system-environment-variables-to-php-fpm-when-using-nginx-a70045370fad

### CODE REVIEW

**Comment by deiucanta** [comment]
@coffee-cup I'm not a Rust dev and I don't know how to fix the test snapshots. Can you do it?

**Comment by aleksrutins** [comment]
Add `\nclear_env=no\n` to `staticAssets["php-fpm.conf"]` in the PHP test snapshots.

**Comment by deiucanta** [comment]
@aleksrutins done

**Review by coffee-cup — APPROVED** [review]
Thanks 😄

**Pull request merged**
