### PR TITLE
fix: openssl should be set to lib

### PR DESCRIPTION
**Pull request by iloveitaly**
Without this,  prisma can't find the libraries and will error out

### CODE REVIEW

**Comment by baptisteArno** [comment]
So that's related to #1030 ? Is there any work around before this is getting merged?

**Comment by iloveitaly** [comment]
@baptisteArno you can manually add openssl as a lib via the `--libs` cli arg

**Review by coffee-cup — APPROVED** [review]

**Comment by coffee-cup** [comment]
Looks like some relevant tests are failing. Could you please look into whats going on there. It might be an issue with older versions of prisma?

**Comment by coffee-cup** [comment]
I'd like to revive this PR as I think it is still needed. Some of the tests are failing and can check it out more deeply next week. It would also be a good idea to add a test for prisma 5

**Pull request closed without merging**
