### PR TITLE
install npm/yarn dependencies from lockfile

### PR DESCRIPTION
**Pull request by coffee-cup**
- Install NPM deps with `npm ci`
- Install Yarn deps with `yarn install --frozen-lockfile`

In both cases this will install deps from the lockfile directly and will not update the lockfile with changes.

### CODE REVIEW

**Review by JakeCooper — APPROVED** [review]

**Comment by devtomio** [comment]
iirc `--frozen-lockfile` is yarn 1 only, yarn 2 and above use `--immutable`

**Comment by coffee-cup** [comment]
> iirc `--frozen-lockfile` is yarn 1 only, yarn 2 and above use `--immutable`

Only Yarn 1 is supported at the moment. A second provider will most likely have to be added for Yarn 2 (or we will have to detect and install the proper Nix packages in the current Yarn provider)

**Comment by coffee-cup** [comment]
In fact, I can't seem to find a Yarn 2 package on [Nix packages](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=yarn) so we will probably have to provide that derivation ourselves.

**Comment by devtomio** [comment]
> In fact, I can't seem to find a Yarn 2 package on [Nix packages](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=yarn) so we will probably have to provide that derivation ourselves.

one would just need to detect the `.yarnrc.yml` to detect if an app is running on yarn >2

**Pull request merged**
