### PR TITLE
use absolute paths for compatibility with podman

### PR DESCRIPTION
**Pull request by Lunarequest**
This PR... resolves railwayapp/nixpacks/discussions/121 by using absolutes paths over relative paths for mount points as podman is currently incompatible with docker's behavior. There is an issue upstream to fix this but it would be faster to work around the issue downstream rather then fix it upstream in buildah and waiting for a podman issue to include it.

### CODE REVIEW

**Review by Milo123459 — APPROVED** [review]

**Comment by Milo123459** [comment]
Could it potentially be worth adding Podman tests in CI? cc @coffee-cup

**Comment by Lunarequest** [comment]
In my opinion it would not be worth it for the following reasons.
1. Podman usually is 100% compatible with docker
2. This incompatibility was the result of undocumented behavior on dockers side
3. Other then this the only compatibility issue would be new features added to docker which can't be fixed down stream.

**Comment by Milo123459** [comment]
If you can figure out a way to make all the docker tests run with podman as well (and in parallel, so the docker and podman tests run at the same time) then I think that would be a good idea.

**Comment by Lunarequest** [comment]
I will do my best, is there an irc/matrix/discord where I could ask questions

**Comment by Milo123459** [comment]
https://discord.gg/railway

**Comment by Milo123459** [comment]
Yeah, the account pushing the commit isn't on GitHub. I will trigger it.

**Comment by Lunarequest** [comment]
not at all :/

**Pull request merged**
