### PR TITLE
Install binutils in base docker image

### PR DESCRIPTION
**Pull request by Milo123459**
## What does this PR address?

`ar` has been shown to not be installed in some cases and causes issues. This should fix it.

## Before submitting:

- [x] Make sure to follow [GitHub's guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) on creating PR.
- [x] Did you read through [contribution guidelines](https://github.com/railwayapp/nixpacks/blob/main/CONTRIBUTING.md)?
- [ ] Did your changes require updates to the documentation? Have you updated those accordingly?
- [ ] Did you write tests to cover your changes? Did it pass locally when running `cargo test`?
- [ ] Have you run `cargo fmt`, `cargo check` and `cargo clippy` locally to ensure that CI passes?

### CODE REVIEW

**Comment by coffee-cup** [comment]
What is the base image size increase with this? The last I checked it was fairly large. 

I think we should prefer to install this only as needed (for specific packages or providers) as opposed to first installing it in the base image. Does this even fix the Rust issues?

**Comment by Milo123459** [comment]
> What is the base image size increase with this? The last I checked it was fairly large.
> 
> I think we should prefer to install this only as needed (for specific packages or providers) as opposed to first installing it in the base image. Does this even fix the Rust issues?

I'm not exactly sure how to check the increase.

Though, installing only when needed is extremely hard. We can't just read build scripts and know when a binutils command is being invocated. And, issues with `ar` not being installed would be fixed by this.

**Comment by coffee-cup** [comment]
> I'm not exactly sure how to check the increase.

Build the base image locally before and after the change. I think it was like a 200MB increase.

> Though, installing only when needed is extremely hard. We can't just read build scripts and know when a binutils command is being invocated. And, issues with ar not being installed would be fixed by this.

That is fair. But this has never been an issue with Node, Python, or Ruby projects. So making all of those images 200MB larger isn't ideal. We could just install `binutils` for Rust projects.

**Comment by Milo123459** [comment]
Before: 420MB
After: 432MB

I think that change is fine.

**Comment by coffee-cup** [comment]
I still think we should add it to the Rust provider first before adding it to the base image. I am not opposed to add it to the base in the future. But the default shouldn't be "add to base image". That is how we end up with a massive base that just has everything.

Secondly, does this fix the Rust issues?

**Comment by Milo123459** [comment]
I'll make this only apply to the rust provider now.

And yes, this fixes the rust issues.

**Comment by Milo123459** [comment]
Alright, CI is passing and now only binutils is installed in the Rust provider.

**Review by coffee-cup — APPROVED** [review]

**Pull request merged**
