### PR TITLE
organise some examples

### LINKED ISSUE #186: Organise examples directory
Each provider should have it's own directory, and in that directory it will have directories containing examples.

### PR DESCRIPTION
**Pull request by Milo123459**
fixes #186

### CODE REVIEW

**Review by coffee-cup — APPROVED** [review]
I'm happy with the refactor but tests should pass before merging

**Comment by Milo123459** [comment]
Unfortunately, I need someone with a Mac or Linux device to make ./examples/shell-hello/start.sh executable, as I have a windows machine and don't have chmod.

**Comment by wyzlle** [comment]
`django` should be renamed to `python-django`.

**Comment by Milo123459** [comment]
I'm having trouble merging in my commits to this branch because it's changed. The branch for this is now on the nixpacks repo, not my fork.

**Comment by coffee-cup** [comment]
I've updated all the paths for failing tests.

**Pull request merged**
