### PR TITLE
fix: do not mutate read-only files

### PR DESCRIPTION
**Pull request by iloveitaly**
Right now, if you attempt to build a project that contains read-only files it will fail with a simple permission error. This makes it impossible for the user
to understand what file is causing issues.

The simple fix used here simply does not mutate the line endings on files which cannot be written.

I'm not sure *why* the line endings are mutated on files or why the entire project directory is copied. I imagine I'm missing something obvious that could cause other downstream impacts,
so I'm opening this PR as the start of a discussion.

This PR:

fixes https://github.com/railwayapp/nixpacks/issues/1071
related https://github.com/railwayapp/nixpacks/issues/700

TODO

- [ ] Tests are added/updated if needed

### CODE REVIEW

**Comment by iloveitaly** [comment]
Friendly reminder regarding this pull request. Please let me know if there are any further updates needed.

**Comment by coffee-cup** [comment]
Hey sorry about the delay. The line endings mutating was added here, https://github.com/railwayapp/nixpacks/pull/436 to fix issues with Windows.

This PR looks good though. Could you please just fix the lining/tests and we can get it merged :)

**Comment by iloveitaly** [comment]
Can you help me with the windows build?

I'm a rust beginner and have no idea what the idiomatic way of handling this sort of thing in rust is.,

**Comment by coffee-cup** [comment]
Of course! You should be able to have a separate `is_writable` function that is used for windows. Similar to this

https://github.com/railwayapp/nixpacks/blob/2df97bbf824d939081598573a643ae818397b39c/src/nixpacks/app.rs#L154

**Comment by iloveitaly** [comment]
Friendly reminder that this pull request may be closed soon if there is no further activity. Let me know if you need any assistance.

**Comment by coffee-cup** [comment]
I've updated the `is_writable` function to support windows. I'll merge after everything passes.

**Review by coffee-cup — APPROVED** [review]

**Pull request merged**
