### PR TITLE
docs: add link to shell completions

### PR DESCRIPTION
**Pull request by iloveitaly**
docs link to zsh shell completions.

### CODE REVIEW

**Comment by brody192** [comment]
Hmmm, I don't think we are too keen about linking out to a repo from a 3rd party.

**Comment by iloveitaly** [comment]
Makes sense. Would you consider bundling this into the nixpacks installation?

**Comment by iloveitaly** [comment]
@coffee-cup do you know where the brew installation logic is? Not sure the best way to package completions into this repo / build system. Point me in the right direction and I'll attempt to make the time for it.

**Comment by coffee-cup** [comment]
@iloveitaly It is in the core Homebrew repo https://github.com/Homebrew/homebrew-core/blob/master/Formula/r/railway.rb

**Pull request closed without merging**
